### ISSUE TITLE
Styling questions

### ISSUE THREAD

**Issue by trobbertze** [rrag/react-stockcharts#310]
Hi

I am struggling a little with styling my chart.

I am trying to achieve the following:
![chart](https://user-images.githubusercontent.com/2182401/28743523-2be3a6be-744c-11e7-9b55-bd31d973b221.png)

The 2 things I am unable to achieve is the border around the chart and styling the HoverTooltip.

Could you please point me in the right direction?

**Comment by rrag** [comment]
for the border around the chart, you could add this to your global css

```css
.react-stockcharts-grabbing-cursor,
.react-stockcharts-crosshair-cursor {
	stroke: #000000;
	stroke-width: 1;
	opacity: 1 !important;
	fill-opacity: 0 !important;
}
```
and for the hover, tooltip I suggest you create a completely custom version of [HoverTooltip](https://github.com/rrag/react-stockcharts/blob/master/src/lib/tooltip/HoverTooltip.js) and use that.
